/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EmployeeStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Time = IDL.Int;
export const EmployeeRecord = IDL.Record({
  'id' : IDL.Text,
  'diplomaFileId' : IDL.Opt(IDL.Text),
  'status' : EmployeeStatus,
  'signatureFileId' : IDL.Opt(IDL.Text),
  'experienceDetails' : IDL.Opt(IDL.Text),
  'ifscCode' : IDL.Text,
  'salarySlip1FileId' : IDL.Opt(IDL.Text),
  'typesOfCalling' : IDL.Vec(IDL.Text),
  'dateOfBirth' : IDL.Text,
  'class10CertFileId' : IDL.Opt(IDL.Text),
  'class12CertFileId' : IDL.Opt(IDL.Text),
  'alternatePhone' : IDL.Opt(IDL.Text),
  'accountHolderName' : IDL.Text,
  'salarySlip2FileId' : IDL.Opt(IDL.Text),
  'fullName' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'bankName' : IDL.Text,
  'passportPhotoFileId' : IDL.Opt(IDL.Text),
  'panCardFileId' : IDL.Opt(IDL.Text),
  'salarySlip3FileId' : IDL.Opt(IDL.Text),
  'leavingLetterFileId' : IDL.Opt(IDL.Text),
  'hasExperience' : IDL.Bool,
  'masterFileId' : IDL.Opt(IDL.Text),
  'postApplying' : IDL.Text,
  'gender' : IDL.Text,
  'bachelorFileId' : IDL.Opt(IDL.Text),
  'upiId' : IDL.Text,
  'panNumber' : IDL.Text,
  'cancelledChequeFileId' : IDL.Opt(IDL.Text),
  'accountNumber' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'phone' : IDL.Text,
  'fullAddress' : IDL.Text,
  'aadhaarCardFileId' : IDL.Opt(IDL.Text),
  'educationLevel' : IDL.Text,
  'experienceCertificateFileId' : IDL.Opt(IDL.Text),
  'declarationDate' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEmployeeRecord' : IDL.Func([IDL.Text], [], []),
  'getAllEmployeeRecords' : IDL.Func([], [IDL.Vec(EmployeeRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployeeCountByStatus' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getEmployeeRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(EmployeeRecord)],
      ['query'],
    ),
  'getEmployeeRecordsByIdPattern' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EmployeeRecord)],
      [],
    ),
  'getEmployeeRecordsByStatus' : IDL.Func(
      [EmployeeStatus],
      [IDL.Vec(EmployeeRecord)],
      ['query'],
    ),
  'getEmployeeRecordsByStatusSorted' : IDL.Func(
      [EmployeeStatus],
      [IDL.Vec(EmployeeRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitEmployeeRecord' : IDL.Func([EmployeeRecord], [IDL.Text], []),
  'updateEmployeeRecord' : IDL.Func(
      [IDL.Text, EmployeeRecord],
      [EmployeeRecord],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EmployeeStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Time = IDL.Int;
  const EmployeeRecord = IDL.Record({
    'id' : IDL.Text,
    'diplomaFileId' : IDL.Opt(IDL.Text),
    'status' : EmployeeStatus,
    'signatureFileId' : IDL.Opt(IDL.Text),
    'experienceDetails' : IDL.Opt(IDL.Text),
    'ifscCode' : IDL.Text,
    'salarySlip1FileId' : IDL.Opt(IDL.Text),
    'typesOfCalling' : IDL.Vec(IDL.Text),
    'dateOfBirth' : IDL.Text,
    'class10CertFileId' : IDL.Opt(IDL.Text),
    'class12CertFileId' : IDL.Opt(IDL.Text),
    'alternatePhone' : IDL.Opt(IDL.Text),
    'accountHolderName' : IDL.Text,
    'salarySlip2FileId' : IDL.Opt(IDL.Text),
    'fullName' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'bankName' : IDL.Text,
    'passportPhotoFileId' : IDL.Opt(IDL.Text),
    'panCardFileId' : IDL.Opt(IDL.Text),
    'salarySlip3FileId' : IDL.Opt(IDL.Text),
    'leavingLetterFileId' : IDL.Opt(IDL.Text),
    'hasExperience' : IDL.Bool,
    'masterFileId' : IDL.Opt(IDL.Text),
    'postApplying' : IDL.Text,
    'gender' : IDL.Text,
    'bachelorFileId' : IDL.Opt(IDL.Text),
    'upiId' : IDL.Text,
    'panNumber' : IDL.Text,
    'cancelledChequeFileId' : IDL.Opt(IDL.Text),
    'accountNumber' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'phone' : IDL.Text,
    'fullAddress' : IDL.Text,
    'aadhaarCardFileId' : IDL.Opt(IDL.Text),
    'educationLevel' : IDL.Text,
    'experienceCertificateFileId' : IDL.Opt(IDL.Text),
    'declarationDate' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEmployeeRecord' : IDL.Func([IDL.Text], [], []),
    'getAllEmployeeRecords' : IDL.Func(
        [],
        [IDL.Vec(EmployeeRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployeeCountByStatus' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getEmployeeRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(EmployeeRecord)],
        ['query'],
      ),
    'getEmployeeRecordsByIdPattern' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EmployeeRecord)],
        [],
      ),
    'getEmployeeRecordsByStatus' : IDL.Func(
        [EmployeeStatus],
        [IDL.Vec(EmployeeRecord)],
        ['query'],
      ),
    'getEmployeeRecordsByStatusSorted' : IDL.Func(
        [EmployeeStatus],
        [IDL.Vec(EmployeeRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitEmployeeRecord' : IDL.Func([EmployeeRecord], [IDL.Text], []),
    'updateEmployeeRecord' : IDL.Func(
        [IDL.Text, EmployeeRecord],
        [EmployeeRecord],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };