/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EmployeeRecord {
  'id' : string,
  'diplomaFileId' : [] | [string],
  'status' : EmployeeStatus,
  'signatureFileId' : [] | [string],
  'experienceDetails' : [] | [string],
  'ifscCode' : string,
  'salarySlip1FileId' : [] | [string],
  'typesOfCalling' : Array<string>,
  'dateOfBirth' : string,
  'class10CertFileId' : [] | [string],
  'class12CertFileId' : [] | [string],
  'alternatePhone' : [] | [string],
  'accountHolderName' : string,
  'salarySlip2FileId' : [] | [string],
  'fullName' : string,
  'submittedAt' : Time,
  'email' : string,
  'bankName' : string,
  'passportPhotoFileId' : [] | [string],
  'panCardFileId' : [] | [string],
  'salarySlip3FileId' : [] | [string],
  'leavingLetterFileId' : [] | [string],
  'hasExperience' : boolean,
  'masterFileId' : [] | [string],
  'postApplying' : string,
  'gender' : string,
  'bachelorFileId' : [] | [string],
  'upiId' : string,
  'panNumber' : string,
  'cancelledChequeFileId' : [] | [string],
  'accountNumber' : string,
  'aadhaarNumber' : string,
  'phone' : string,
  'fullAddress' : string,
  'aadhaarCardFileId' : [] | [string],
  'educationLevel' : string,
  'experienceCertificateFileId' : [] | [string],
  'declarationDate' : string,
}
export type EmployeeStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'inactive' : null };
export type Time = bigint;
export interface _SERVICE {
  'changeAdminPassword' : ActorMethod<[string, string], boolean>,
  'deleteEmployeeRecord' : ActorMethod<[string], undefined>,
  'getAcceptanceLetter' : ActorMethod<[string], [] | [string]>,
  'getAllAcceptanceLetters' : ActorMethod<[], Array<[string, string]>>,
  'getAllEmployeeRecords' : ActorMethod<[], Array<EmployeeRecord>>,
  'getDocumentBlob' : ActorMethod<[string], [] | [Uint8Array]>,
  'getEmployeeCountByStatus' : ActorMethod<[string], bigint>,
  'getEmployeeRecord' : ActorMethod<[string], [] | [EmployeeRecord]>,
  'getEmployeeRecordsByIdPattern' : ActorMethod<
    [string],
    Array<EmployeeRecord>
  >,
  'getEmployeeRecordsByStatus' : ActorMethod<
    [EmployeeStatus],
    Array<EmployeeRecord>
  >,
  'getEmployeeRecordsByStatusSorted' : ActorMethod<
    [EmployeeStatus],
    Array<EmployeeRecord>
  >,
  'recordAcceptanceLetter' : ActorMethod<[string, string], undefined>,
  'storeDocument' : ActorMethod<[Uint8Array, string], string>,
  'submitEmployeeRecord' : ActorMethod<[EmployeeRecord], string>,
  'updateEmployeeRecord' : ActorMethod<
    [string, EmployeeRecord],
    EmployeeRecord
  >,
  'verifyAdminLogin' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];