/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface EmployeeRecord {
    id: string;
    diplomaFileId?: string;
    status: EmployeeStatus;
    signatureFileId?: string;
    experienceDetails?: string;
    ifscCode: string;
    salarySlip1FileId?: string;
    typesOfCalling: Array<string>;
    dateOfBirth: string;
    class10CertFileId?: string;
    class12CertFileId?: string;
    alternatePhone?: string;
    accountHolderName: string;
    salarySlip2FileId?: string;
    fullName: string;
    submittedAt: Time;
    email: string;
    bankName: string;
    passportPhotoFileId?: string;
    panCardFileId?: string;
    salarySlip3FileId?: string;
    leavingLetterFileId?: string;
    hasExperience: boolean;
    masterFileId?: string;
    postApplying: string;
    gender: string;
    bachelorFileId?: string;
    upiId: string;
    panNumber: string;
    cancelledChequeFileId?: string;
    accountNumber: string;
    aadhaarNumber: string;
    phone: string;
    fullAddress: string;
    aadhaarCardFileId?: string;
    educationLevel: string;
    experienceCertificateFileId?: string;
    declarationDate: string;
}
export enum EmployeeStatus {
    active = "active",
    pending = "pending",
    inactive = "inactive"
}
export interface backendInterface {
    changeAdminPassword(oldHash: string, newHash: string): Promise<boolean>;
    deleteEmployeeRecord(id: string): Promise<void>;
    getAcceptanceLetter(employeeId: string): Promise<string | null>;
    getAllAcceptanceLetters(): Promise<Array<[string, string]>>;
    getAllEmployeeRecords(): Promise<Array<EmployeeRecord>>;
    getDocumentBlob(id: string): Promise<Uint8Array | null>;
    getEmployeeCountByStatus(status: string): Promise<bigint>;
    getEmployeeRecord(id: string): Promise<EmployeeRecord | null>;
    getEmployeeRecordsByIdPattern(pattern: string): Promise<Array<EmployeeRecord>>;
    getEmployeeRecordsByStatus(status: EmployeeStatus): Promise<Array<EmployeeRecord>>;
    getEmployeeRecordsByStatusSorted(status: EmployeeStatus): Promise<Array<EmployeeRecord>>;
    recordAcceptanceLetter(employeeId: string, acceptedDate: string): Promise<void>;
    storeDocument(data: Uint8Array, fileName: string): Promise<string>;
    submitEmployeeRecord(record: EmployeeRecord): Promise<string>;
    updateEmployeeRecord(id: string, updatedRecord: EmployeeRecord): Promise<EmployeeRecord>;
    verifyAdminLogin(username: string, passwordHash: string): Promise<boolean>;
}
import type { EmployeeRecord as _EmployeeRecord, EmployeeStatus as _EmployeeStatus, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async changeAdminPassword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminPassword(arg0, arg1);
            return result;
        }
    }
    async deleteEmployeeRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployeeRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployeeRecord(arg0);
            return result;
        }
    }
    async getAcceptanceLetter(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAcceptanceLetter(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAcceptanceLetter(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAcceptanceLetters(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAcceptanceLetters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAcceptanceLetters();
            return result;
        }
    }
    async getAllEmployeeRecords(): Promise<Array<EmployeeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployeeRecords();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployeeRecords();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentBlob(arg0: string): Promise<Uint8Array | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentBlob(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentBlob(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeCountByStatus(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeCountByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeCountByStatus(arg0);
            return result;
        }
    }
    async getEmployeeRecord(arg0: string): Promise<EmployeeRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeRecord(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeRecord(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeRecordsByIdPattern(arg0: string): Promise<Array<EmployeeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeRecordsByIdPattern(arg0);
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeRecordsByIdPattern(arg0);
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeRecordsByStatus(arg0: EmployeeStatus): Promise<Array<EmployeeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeRecordsByStatus(to_candid_EmployeeStatus_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeRecordsByStatus(to_candid_EmployeeStatus_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeRecordsByStatusSorted(arg0: EmployeeStatus): Promise<Array<EmployeeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeRecordsByStatusSorted(to_candid_EmployeeStatus_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeRecordsByStatusSorted(to_candid_EmployeeStatus_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordAcceptanceLetter(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAcceptanceLetter(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAcceptanceLetter(arg0, arg1);
            return result;
        }
    }
    async storeDocument(arg0: Uint8Array, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.storeDocument(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeDocument(arg0, arg1);
            return result;
        }
    }
    async submitEmployeeRecord(arg0: EmployeeRecord): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEmployeeRecord(to_candid_EmployeeRecord_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEmployeeRecord(to_candid_EmployeeRecord_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateEmployeeRecord(arg0: string, arg1: EmployeeRecord): Promise<EmployeeRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployeeRecord(arg0, to_candid_EmployeeRecord_n11(this._uploadFile, this._downloadFile, arg1));
                return from_candid_EmployeeRecord_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployeeRecord(arg0, to_candid_EmployeeRecord_n11(this._uploadFile, this._downloadFile, arg1));
            return from_candid_EmployeeRecord_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyAdminLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminLogin(arg0, arg1);
            return result;
        }
    }
}
function from_candid_EmployeeRecord_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeRecord): EmployeeRecord {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_EmployeeStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeStatus): EmployeeStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmployeeRecord]): EmployeeRecord | null {
    return value.length === 0 ? null : from_candid_EmployeeRecord_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    diplomaFileId: [] | [string];
    status: _EmployeeStatus;
    signatureFileId: [] | [string];
    experienceDetails: [] | [string];
    ifscCode: string;
    salarySlip1FileId: [] | [string];
    typesOfCalling: Array<string>;
    dateOfBirth: string;
    class10CertFileId: [] | [string];
    class12CertFileId: [] | [string];
    alternatePhone: [] | [string];
    accountHolderName: string;
    salarySlip2FileId: [] | [string];
    fullName: string;
    submittedAt: _Time;
    email: string;
    bankName: string;
    passportPhotoFileId: [] | [string];
    panCardFileId: [] | [string];
    salarySlip3FileId: [] | [string];
    leavingLetterFileId: [] | [string];
    hasExperience: boolean;
    masterFileId: [] | [string];
    postApplying: string;
    gender: string;
    bachelorFileId: [] | [string];
    upiId: string;
    panNumber: string;
    cancelledChequeFileId: [] | [string];
    accountNumber: string;
    aadhaarNumber: string;
    phone: string;
    fullAddress: string;
    aadhaarCardFileId: [] | [string];
    educationLevel: string;
    experienceCertificateFileId: [] | [string];
    declarationDate: string;
}): {
    id: string;
    diplomaFileId?: string;
    status: EmployeeStatus;
    signatureFileId?: string;
    experienceDetails?: string;
    ifscCode: string;
    salarySlip1FileId?: string;
    typesOfCalling: Array<string>;
    dateOfBirth: string;
    class10CertFileId?: string;
    class12CertFileId?: string;
    alternatePhone?: string;
    accountHolderName: string;
    salarySlip2FileId?: string;
    fullName: string;
    submittedAt: Time;
    email: string;
    bankName: string;
    passportPhotoFileId?: string;
    panCardFileId?: string;
    salarySlip3FileId?: string;
    leavingLetterFileId?: string;
    hasExperience: boolean;
    masterFileId?: string;
    postApplying: string;
    gender: string;
    bachelorFileId?: string;
    upiId: string;
    panNumber: string;
    cancelledChequeFileId?: string;
    accountNumber: string;
    aadhaarNumber: string;
    phone: string;
    fullAddress: string;
    aadhaarCardFileId?: string;
    educationLevel: string;
    experienceCertificateFileId?: string;
    declarationDate: string;
} {
    return {
        id: value.id,
        diplomaFileId: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.diplomaFileId)),
        status: from_candid_EmployeeStatus_n5(_uploadFile, _downloadFile, value.status),
        signatureFileId: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.signatureFileId)),
        experienceDetails: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.experienceDetails)),
        ifscCode: value.ifscCode,
        salarySlip1FileId: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.salarySlip1FileId)),
        typesOfCalling: value.typesOfCalling,
        dateOfBirth: value.dateOfBirth,
        class10CertFileId: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.class10CertFileId)),
        class12CertFileId: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.class12CertFileId)),
        alternatePhone: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.alternatePhone)),
        accountHolderName: value.accountHolderName,
        salarySlip2FileId: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.salarySlip2FileId)),
        fullName: value.fullName,
        submittedAt: value.submittedAt,
        email: value.email,
        bankName: value.bankName,
        passportPhotoFileId: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.passportPhotoFileId)),
        panCardFileId: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.panCardFileId)),
        salarySlip3FileId: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.salarySlip3FileId)),
        leavingLetterFileId: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.leavingLetterFileId)),
        hasExperience: value.hasExperience,
        masterFileId: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.masterFileId)),
        postApplying: value.postApplying,
        gender: value.gender,
        bachelorFileId: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.bachelorFileId)),
        upiId: value.upiId,
        panNumber: value.panNumber,
        cancelledChequeFileId: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.cancelledChequeFileId)),
        accountNumber: value.accountNumber,
        aadhaarNumber: value.aadhaarNumber,
        phone: value.phone,
        fullAddress: value.fullAddress,
        aadhaarCardFileId: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.aadhaarCardFileId)),
        educationLevel: value.educationLevel,
        experienceCertificateFileId: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.experienceCertificateFileId)),
        declarationDate: value.declarationDate
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    inactive: null;
}): EmployeeStatus {
    return "active" in value ? EmployeeStatus.active : "pending" in value ? EmployeeStatus.pending : "inactive" in value ? EmployeeStatus.inactive : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmployeeRecord>): Array<EmployeeRecord> {
    return value.map((x)=>from_candid_EmployeeRecord_n3(_uploadFile, _downloadFile, x));
}
function to_candid_EmployeeRecord_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeRecord): _EmployeeRecord {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_EmployeeStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeStatus): _EmployeeStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    diplomaFileId?: string;
    status: EmployeeStatus;
    signatureFileId?: string;
    experienceDetails?: string;
    ifscCode: string;
    salarySlip1FileId?: string;
    typesOfCalling: Array<string>;
    dateOfBirth: string;
    class10CertFileId?: string;
    class12CertFileId?: string;
    alternatePhone?: string;
    accountHolderName: string;
    salarySlip2FileId?: string;
    fullName: string;
    submittedAt: Time;
    email: string;
    bankName: string;
    passportPhotoFileId?: string;
    panCardFileId?: string;
    salarySlip3FileId?: string;
    leavingLetterFileId?: string;
    hasExperience: boolean;
    masterFileId?: string;
    postApplying: string;
    gender: string;
    bachelorFileId?: string;
    upiId: string;
    panNumber: string;
    cancelledChequeFileId?: string;
    accountNumber: string;
    aadhaarNumber: string;
    phone: string;
    fullAddress: string;
    aadhaarCardFileId?: string;
    educationLevel: string;
    experienceCertificateFileId?: string;
    declarationDate: string;
}): {
    id: string;
    diplomaFileId: [] | [string];
    status: _EmployeeStatus;
    signatureFileId: [] | [string];
    experienceDetails: [] | [string];
    ifscCode: string;
    salarySlip1FileId: [] | [string];
    typesOfCalling: Array<string>;
    dateOfBirth: string;
    class10CertFileId: [] | [string];
    class12CertFileId: [] | [string];
    alternatePhone: [] | [string];
    accountHolderName: string;
    salarySlip2FileId: [] | [string];
    fullName: string;
    submittedAt: _Time;
    email: string;
    bankName: string;
    passportPhotoFileId: [] | [string];
    panCardFileId: [] | [string];
    salarySlip3FileId: [] | [string];
    leavingLetterFileId: [] | [string];
    hasExperience: boolean;
    masterFileId: [] | [string];
    postApplying: string;
    gender: string;
    bachelorFileId: [] | [string];
    upiId: string;
    panNumber: string;
    cancelledChequeFileId: [] | [string];
    accountNumber: string;
    aadhaarNumber: string;
    phone: string;
    fullAddress: string;
    aadhaarCardFileId: [] | [string];
    educationLevel: string;
    experienceCertificateFileId: [] | [string];
    declarationDate: string;
} {
    return {
        id: value.id,
        diplomaFileId: value.diplomaFileId ? candid_some(value.diplomaFileId) : candid_none(),
        status: to_candid_EmployeeStatus_n9(_uploadFile, _downloadFile, value.status),
        signatureFileId: value.signatureFileId ? candid_some(value.signatureFileId) : candid_none(),
        experienceDetails: value.experienceDetails ? candid_some(value.experienceDetails) : candid_none(),
        ifscCode: value.ifscCode,
        salarySlip1FileId: value.salarySlip1FileId ? candid_some(value.salarySlip1FileId) : candid_none(),
        typesOfCalling: value.typesOfCalling,
        dateOfBirth: value.dateOfBirth,
        class10CertFileId: value.class10CertFileId ? candid_some(value.class10CertFileId) : candid_none(),
        class12CertFileId: value.class12CertFileId ? candid_some(value.class12CertFileId) : candid_none(),
        alternatePhone: value.alternatePhone ? candid_some(value.alternatePhone) : candid_none(),
        accountHolderName: value.accountHolderName,
        salarySlip2FileId: value.salarySlip2FileId ? candid_some(value.salarySlip2FileId) : candid_none(),
        fullName: value.fullName,
        submittedAt: value.submittedAt,
        email: value.email,
        bankName: value.bankName,
        passportPhotoFileId: value.passportPhotoFileId ? candid_some(value.passportPhotoFileId) : candid_none(),
        panCardFileId: value.panCardFileId ? candid_some(value.panCardFileId) : candid_none(),
        salarySlip3FileId: value.salarySlip3FileId ? candid_some(value.salarySlip3FileId) : candid_none(),
        leavingLetterFileId: value.leavingLetterFileId ? candid_some(value.leavingLetterFileId) : candid_none(),
        hasExperience: value.hasExperience,
        masterFileId: value.masterFileId ? candid_some(value.masterFileId) : candid_none(),
        postApplying: value.postApplying,
        gender: value.gender,
        bachelorFileId: value.bachelorFileId ? candid_some(value.bachelorFileId) : candid_none(),
        upiId: value.upiId,
        panNumber: value.panNumber,
        cancelledChequeFileId: value.cancelledChequeFileId ? candid_some(value.cancelledChequeFileId) : candid_none(),
        accountNumber: value.accountNumber,
        aadhaarNumber: value.aadhaarNumber,
        phone: value.phone,
        fullAddress: value.fullAddress,
        aadhaarCardFileId: value.aadhaarCardFileId ? candid_some(value.aadhaarCardFileId) : candid_none(),
        educationLevel: value.educationLevel,
        experienceCertificateFileId: value.experienceCertificateFileId ? candid_some(value.experienceCertificateFileId) : candid_none(),
        declarationDate: value.declarationDate
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeStatus): {
    active: null;
} | {
    pending: null;
} | {
    inactive: null;
} {
    return value == EmployeeStatus.active ? {
        active: null
    } : value == EmployeeStatus.pending ? {
        pending: null
    } : value == EmployeeStatus.inactive ? {
        inactive: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
